---
- hosts: kube
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - include_tasks: tasks/vagrant-setup.yml

  roles:
    - geerlingguy.security
    - geerlingguy.swap
    - geerlingguy.docker
    - geerlingguy.kubernetes
